<?xml version="1.0" encoding="UTF-8" ?>
<schema targetNamespace="http://www.doleckovi.cz/piskvorky/api/types" elementFormDefault="qualified"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:p="http://www.doleckovi.cz/piskvorky/api/types">
	<simpleType name="Stone">
		<restriction base="string">
			<enumeration value="WHITE"/>
			<enumeration value="BLACK"/>
		</restriction>
	</simpleType>
	<simpleType name="Coordinate">
		<restriction base="nonNegativeInteger">
			<maxInclusive value="63"/>
		</restriction>
	</simpleType>
	<simpleType name="BoardSize">
		<restriction base="positiveInteger">
			<minInclusive value="5"/>
			<maxInclusive value="64"/>
		</restriction>
	</simpleType>
	<complexType name="Board">
		<attribute name="width" type="p:BoardSize" use="required"/>
		<attribute name="height" type="p:BoardSize" use="required"/>
	</complexType>
	<complexType name="Move">
		<attribute name="column" type="p:Coordinate" use="required"/>
		<attribute name="line" type="p:Coordinate" use="required"/>
		<attribute name="player" type="p:Stone" use="required"/>
	</complexType>
	<complexType name="MoveList">
		<sequence>
			<element name="move" type="p:Move" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="finished" type="boolean"/>
	</complexType>
	<complexType name="Player">
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="PlayerList">
		<sequence>
			<element name="white" type="p:Player"/>
			<element name="black" type="p:Player"/>
		</sequence>
	</complexType>
	<complexType name="Game">
		<sequence>
			<element name="board" type="p:Board"/>
			<element name="players" type="p:PlayerList"/>
			<element name="moves" type="p:MoveList"/>
		</sequence>
	</complexType>
	<element name="game" type="p:Game"/>
</schema>